# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_call:
    inputs:
      skip_integration_tests:
        description: "Skip integration tests"
        required: false
        type: boolean
        default: false

env:
  mvn_options: --batch-mode -Dstyle.color=always -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
  SERVICE_ACCOUNT_SECRET: ${{ secrets.SERVICE_ACCOUNT_SECRET }}

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 17, 21 ]
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Jdk ${{ matrix.java-version }}, os ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          if [ "${{ inputs.skip_integration_tests }}" = "true" ]; then
            ./mvnw ${{ env.mvn_options }} -DskipBigQueryIntegrationTests=true verify --file pom.xml
          else
            ./mvnw ${{ env.mvn_options }} verify --file pom.xml
          fi
        shell: bash
