# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: datafaker-net/datafaker-gen/.github/workflows/ci.yml@ci
    with:
      skip_integration_tests: false